### ISSUE TITLE
Make it compatible with Autofac 4

### ISSUE THREAD

**Issue by Lisaj** [autofac/Autofac.Mvc.Owin#1]

**Comment by tillig** [comment]
Hi! We're slowly and surely making our way through the 20+ integration libraries we support along with core Autofac. [The overall status of everything is tracked here.](https://github.com/autofac/Autofac/issues/594)

If you're interested in updates, subscribe to that issue. I'll keep this one open so people know where to look, but updates will probably be over there.

**Comment by Lisaj** [comment]
Thank you for the information

**Comment by tillig** [comment]
We published [version 4.0.0 with Autofac 4 compatibility](https://www.nuget.org/packages/Autofac.Mvc5.Owin/4.0.0) on August 10, 2016.
