### ISSUE TITLE
Update to support .NET 4.5

### ISSUE THREAD

**Issue by tillig** [autofac/Autofac.Mvc.Owin#2]
If we can get Autofac.Mvc5 to support .NET 4.5 we can update this package, too.

See: Autofac/Autofac.Mvc#15

**Comment by tillig** [comment]
Autofac.Owin already has .NET 4.5 support.

**Comment by alexmg** [comment]
I have pushed new packages to MyGet that target .NET Framework 4.5.

- Autofac.Mvc5 - 4.0.1-CI-235
- Autofac.Mvc5.Owin - 4.0.1-CI-222

These are awaiting testing. If all goes well I will push them over to NuGet as release packages.

https://www.myget.org/F/autofac/api/v2/

**Comment by alexmg** [comment]
I've pushed the two packages over to NuGet as release packages.
